#ifndef ANCS_PROTOCOL_CONSTANTS_H
#define ANCS_PROTOCOL_CONSTANTS_H

#define ANCS_SERVICE_UUID "7905F431-B5CE-4E99-A40F-4B1E122D00D0"

#define ANCS_NOTIFICATION_SOURCE_CHARACTERISTIC_UUID "9FBF120D-6301-42D9-8C58-25E699A21DBD"
#define ANCS_CONTROL_POINT_CHARACTERISTIC_UUID "69D1D8F3-45E1-49A8-9821-9BBDFDAAD9D9"
#define ANCS_DATA_SOURCE_CHARACTERISTIC_UUID "22EAC6E9-24D6-4BB5-BE44-B36ACE7C7BFB"

#define ANCS_CATEGORY_ID_OTHER 0
#define ANCS_CATEGORY_ID_INCOMING_CALL 1
#define ANCS_CATEGORY_ID_MISSED_CALL 2
#define ANCS_CATEGORY_ID_VOICEMAIL 3
#define ANCS_CATEGORY_ID_SOCIAL 4
#define ANCS_CATEGORY_ID_SCHEDULE 5
#define ANCS_CATEGORY_ID_EMAIL 6
#define ANCS_CATEGORY_ID_NEWS 7
#define ANCS_CATEGORY_ID_HEALTH_AND_FITNESS 8
#define ANCS_CATEGORY_ID_BUSINESS_AND_FINANCE 9
#define ANCS_CATEGORY_ID_LOCATION 10
#define ANCS_CATEGORY_ID_ENTERTAINMENT 11

#define ANCS_EVENT_ID_NOTIFICATION_ADDED 0
#define ANCS_EVENT_ID_NOTIFICATION_MODIFIED 1
#define ANCS_EVENT_ID_NOTIFICATION_REMOVED 2

#define ANCS_EVENT_FLAG_SILENT (1 << 0)
#define ANCS_EVENT_FLAG_IMPORTANT (1 << 1)
#define ANCS_EVENT_FLAG_PRE_EXISTING (1 << 2)
#define ANCS_EVENT_FLAG_POSITIVE_ACTION (1 << 3)
#define ANCS_EVENT_FLAG_NEGATIVE_ACTION (1 << 4)

#define ANCS_COMMAND_ID_GET_NOTIFICATION_ATTRIBUTES 0
#define ANCS_COMMAND_ID_GET_APP_ATTRIBUTES 1
#define ANCS_COMMAND_ID_PERFORM_NOTIFICATION_ACTION 2

#define ANCS_NOTIFICATION_ATTRIBUTE_ID_APP_IDENTIFIER 0
#define ANCS_NOTIFICATION_ATTRIBUTE_ID_TITLE 1
#define ANCS_NOTIFICATION_ATTRIBUTE_ID_SUBTITLE 2
#define ANCS_NOTIFICATION_ATTRIBUTE_ID_MESSAGE 3
#define ANCS_NOTIFICATION_ATTRIBUTE_ID_MESSAGE_SIZE 4
#define ANCS_NOTIFICATION_ATTRIBUTE_ID_DATE 5
#define ANCS_NOTIFICATION_ATTRIBUTE_ID_POSITIVE_ACTION_LABEL 6
#define ANCS_NOTIFICATION_ATTRIBUTE_ID_NEGATIVE_ACTION_LABEL 7

#define ANCS_ACTIONIDPOSITIVE 0
#define ANCS_ACTIONIDNEGATIVE 1

#define ANCS_APP_ATTRIBUTE_IDDISPLAY_NAME 0

#endif // ANCS_PROTOCOL_CONSTANTS_H
